// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using DbFirst.Entities;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace DbFirst
{
    public partial interface IAppDBContextProcedures
    {
        Task<List<usp_getproductResult>> usp_getproductAsync(int? ProductId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
